run:
  tests: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam

issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  goimports:
    local-prefixes: gitlab.com/riccardom/cosmos-go-wallet
  dogsled:
    max-blank-identifiers: 3
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
